services:
  api:
    build: .
    ports:
      - "8000:8000"
    secrets:
      - db_url
    environment:
      - DB_URL_FILE=/run/secrets/db_url

  db:
    image: postgres:13
    secrets:
      - db_password
    environment:
      POSTGRES_PASSWORD_FILE: /run/secrets/db_password

secrets:
  db_url:
    file: ./secrets/db_url.txt
  db_password:
    file: ./secrets/db_password.txt