services:
  api:
    build: .
    dns:  # Avoid temporary failure on name resolution on pip installs
      - 8.8.8.8
      - 8.8.4.4
    ports:
      - "8000:8000"
    environment:
      PYTHONPATH: /app
      DB_URL: postgresql+asyncpg://postgres:pwd@db:5432/mytdb
      PORT: 8000
    env_file: .env.dev
    depends_on:
      - db

  db:
    image: postgres:13
    environment:
      POSTGRES_USER: postgres  # Default user with superuser privileges
      POSTGRES_PASSWORD: pwd
      POSTGRES_DB: mytdb
    volumes:
      - postgres_data:/var/lib/postgresql/data

volumes:
  postgres_data: