[tool.poetry]
name = "myt-assignment"
version = "0.1.0"
description = ""
authors = ["Ventura <jorgemzv7@gmail.com>"]
readme = "README.md"
packages = [{include = "myt_assignment"}]

[tool.poetry.dependencies]
python = "^3.11"
fastapi = "^0.115.12"
uvicorn = "^0.34.0"
pydantic = "^2.0.0"
email-validator = "^2.2.0"
sqlalchemy = {extras = ["asyncio"], version = "^2.0.40"}
asyncpg = "^0.30.0"


[tool.poetry.group.dev.dependencies]
pytest = "^8.3.5"
sqlalchemy2-stubs = "^0.0.2a38"
mypy = "^1.15.0"
pylint = "^3.3.6"
python-dotenv = "^1.1.0"
alembic = "^1.15.2"
pytest-asyncio = "^0.26.0"
httpx = "^0.28.1"
pytest-cov = "^6.0.0"
fastapi = "^0.115.12"
sqlalchemy = "^2.0.40"
asyncpg = "^0.30.0"

[build-system]
requires = ["poetry-core"]
build-backend = "poetry.core.masonry.api"

[tool.pytest.ini_options]
asyncio_mode = "auto"
addopts = "--asyncio-mode=auto"